{% set name = "olas" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/olas-{{ version }}.tar.gz
  sha256: f7cd2fa10ef2a09b6bd59309dceaca4f78a897af7fec5c9ea3b02d569d2ea126

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - poetry
  run:
    - cartopy >=0.21.1,<0.22.0
    - dask >=2023.3.1,<2024.0.0
    - matplotlib-base >=3.7.1,<4.0.0
    - netcdf4 >=1.6.3,<2.0.0
    - numpy >=1.24.2,<2.0.0
    - python >={{ python_min }},<4.0
    - scipy >=1.10.1,<2.0.0
    - xarray >=2023.1.0,<2024.0.0

test:
  imports:
    - olas
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jorgeperezg/olas
  summary: Library with wave tools like ESTELA
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jorgeperezg
