{% set name = "olas" %}
{% set version = "0.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/olas-{{ version }}.tar.gz
  sha256: f7cd2fa10ef2a09b6bd59309dceaca4f78a897af7fec5c9ea3b02d569d2ea126

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python {{ python_min }}
    - hatchling
  run:
    - cartopy >=0.21.1
    - dask >=2023.3.1
    - matplotlib-base >=3.7.1
    - netcdf4 >=1.6.3
    - numpy >=1.24.2
    - python >=3.9,<3.14
    - scipy >=1.10.1
    - xarray >=2023.1.0

test:
  imports:
    - olas
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jorgeperezg/olas
  summary: Library with wave tools like ESTELA
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jorgeperezg
